name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint

    - name: Test env vars for python
      run: python -c 'import os;print(os.environ)'
      env:
        AWS_ACCESS_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
